GET http://localhost:3000/products

### 페이지조회

GET http://localhost:3000/products?page=1&sort=favorite&pageSize=5&keyword=%EA%B0%A4%EB%9F%AD%EC%8B%9C


### 상세조회
GET http://localhost:3000/products/66b572268810a4d3286c9c65


# {
#   "id": "66b572268810a4d3286c9c65",
#     "name": "국지니빵",
#     "description": "ㅇㄹㄴㄹㅇㄴㄹㄴㄹㄴㅇㄹㄴㄹㄴㄹㄴㅇ",
#     "price": 34000,
#     "tags": [
#       "strin"
#     ],
#     "images": [],
#     "createdAt": "2024-08-09T01:34:30.503Z",
# }

### 게시물 게시

POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "두바이초콜릿",
    "description": "ㅇㄹㄴㄹㅇㄴㄹㄴㄹㄴㅇㄹㄴㄹㄴㄹㄴㅇ",
    "price": 34000,
  "tags": ["strin"]
}


### 게시물 수정

PATCH  http://localhost:3000/products/66b573e38810a4d3286c9c77
Content-Type: application/json

{
    "name": "국지니빵",
    "description": "ㅇㄹㄴㄹㅇㄴㄹㄴㄹㄴㅇㄹㄴㄹㄴㄹㄴㅇ",
    "price": 34000
   
}

### 게시물 삭제
DELETE  http://localhost:3000/products/66b573e38810a4d3286c9c77