GET http://localhost:3000/products

###
GET http://localhost:3000/products?page=1&pageSize=10&search=post

###
GET http://localhost:3000/products/66b073b7f091c1212931ee68

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "휴지",
  "description": "각휴지",
  "price": "12000",
  "tags": ["천연펄프", "중고"]
}

###
PATCH http://localhost:3000/products/66b89e1f1224fef1326281b9
Content-Type: application/json

{
  "name": "고급 휴지",
  "price": "22000"
}

###
DELETE http://localhost:3000/products/66b22133f55d6c02edc2b2e0