### 상품 목록 조회
GET http://localhost:3000/api/products

### 상품 상세 조회
GET http://localhost:3000/api/products/66b1b0b387dc5032c2ca9f19

### 상품 등록
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "레인 부츠",
  "description": "새로 추가한 상품입니다",
  "price": 55000,
  "tags": ["신발", "레인부츠"]
}

### 상품 수정
PATCH http://localhost:3000/api/products/66b1b7c15e3b2fd5a36d7efd
Content-Type: application/json

{
  "price": 26000
}

### 상품 삭제
DELETE http://localhost:3000/api/products/66b1b7c15e3b2fd5a36d7efd