// 상품 등록 API 확인
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "마사지건",
  "description": "미니 진동 휴대용 마사지건 365g",
  "price": 30000,
  "tag": ["마사지건", "미니", "소형"],
  "images": ["https://kingguide.co.kr/wp-content/uploads/2023/12/%EB%AF%B8%EB%8B%88-%EC%A7%84%EB%8F%99-%ED%9C%B4%EB%8C%80%EC%9A%A9-%EB%A7%88%EC%82%AC%EC%A7%80%EA%B1%B4-365g.webp"]
}

###
// 상품 상세 조회 API 확인
GET http://localhost:3000/products/66b2c717f84a2c6fff728421


###
// 상품 목록 조회 API 확인
GET http://localhost:3000/products?limit=2&sort=recent&search=apple

###
// 상품 수정 API 확인
PATCH http://localhost:3000/products/66b2c717f84a2c6fff728432
Content-Type: application/json

{
  "price": 460000,
  "tags": ["apple", "iPad", "포터블", "태블릿"]
}


###
// 상품 삭제 API 확인
DELETE http://localhost:3000/products/66b2c82b5713df90494dabec


