
### 게시글 조회
GET https://articles-2bks.onrender.com/article


### 게시글 등록
POST https://articles-2bks.onrender.com/article
Content-Type: application/json

{
  "title" : "title 테스트 입니다.",
  "content" : "content 테스트 입니다."
}

### 게시글 수정

PATCH https://articles-2bks.onrender.com/article/8824bdb0-e612-495c-ae01-a78b2a217113
Content-Type: application/json

{
  "title" : "title 변경 테스트 입니다.",
  "content" : "content 변경 테스트 입니다."
}
### 게시글 삭제

DELETE https://articles-2bks.onrender.com/article/8824bdb0-e612-495c-ae01-a78b2a217113



### 댓글 추가
POST https://articles-2bks.onrender.com/article/6f664bcf-4573-4e25-8167-60773dcaff3e/comment
Content-Type: application/json

{
  "content" : "comment 테스트 입니다."
}
### 댓글 수정
PATCH https://articles-2bks.onrender.com/article/6f664bcf-4573-4e25-8167-60773dcaff3e/comment/94b10748-3cb3-4181-9780-04de0f7a7bd0
Content-Type: application/json

{
  "content" : "PATCH comment 테스트 입니다."
}

### 댓글 조회
GET https://articles-2bks.onrender.com/article/6f664bcf-4573-4e25-8167-60773dcaff3e/comment

### 댓글 삭제
DELETE https://articles-2bks.onrender.com/article/6f664bcf-4573-4e25-8167-60773dcaff3e/comment/94b10748-3cb3-4181-9780-04de0f7a7bd0