export const BoardComments = [
  {
    content: "기기 상태를 사진으로 확인할 수 있을까요?",
    postId: 1,
    boardType: "board",
    author: "박서준",
  },
  {
    content: "해당 자전거의 브랜드와 모델명이 궁금합니다.",
    postId: 2,
    boardType: "board",
    author: "김태희",
  },
  {
    content: "책상과 의자의 상태를 좀 더 자세히 알고 싶어요.",
    postId: 8,
    boardType: "board",
    author: "정유미",
  },
  {
    content: "스피커의 모델명과 구입 연도가 어떻게 되나요?",
    postId: 7,
    boardType: "board",
    author: "조정석",
  },
  {
    content: "전자책 리더기의 화면 크기는 어떻게 되나요?",
    postId: 9,
    boardType: "board",
    author: "하정우",
  },
  {
    content: "스마트워치의 배터리 사용 시간은 어느 정도인가요?",
    postId: 12,
    boardType: "board",
    author: "서강준",
  },
  {
    content: "소파의 색상과 소재에 대해 더 알고 싶어요.",
    postId: 3,
    boardType: "board",
    author: "한지민",
  },
  {
    content: "겨울용 코트의 사이즈와 색상은 무엇인가요?",
    postId: 14,
    boardType: "board",
    author: "이동욱",
  },
  {
    content: "자전거 헬멧의 사이즈가 어떻게 되나요?",
    postId: 6,
    boardType: "board",
    author: "조인성",
  },
  {
    content: "리모컨이나 추가 악세서리가 포함되어 있나요?",
    postId: 4,
    boardType: "board",
    author: "유인나",
  },
  {
    content: "가전제품 세트의 모델명과 구매 연도를 알 수 있을까요?",
    postId: 5,
    boardType: "board",
    author: "김우빈",
  },
  {
    content: "탁구대의 사이즈와 재질에 대해 설명해 주세요.",
    postId: 11,
    boardType: "board",
    author: "김남길",
  },
  {
    content: "미니빔 프로젝터의 해상도와 밝기는 어떤가요?",
    postId: 13,
    boardType: "board",
    author: "장나라",
  },
  {
    content: "중고마켓 이용 후 불만족한 경험을 공유합니다.",
    postId: 27,
    boardType: "board",
    author: "박지영",
  },
];
