export const marketPost = [
  {
    id: 133,
    name: "갤럭시 탭 S7",
    description: "삼성 갤럭시 탭 S7",
    price: 350000,
    tags: [], // 필요한 경우 태그 추가
    images: [
      "https://sprint-fe-project.s3.ap-northeast-2.amazonaws.com/Sprint_Mission/user/3/1721991844193/5146532.png",
    ],
    ownerId: 1,
    favoriteCount: 6,
    ownerNickname: "지민",
    isFavorite: false,
  },
  {
    id: 132,
    name: "보스 헤드폰",
    description: "보스 노이즈 캔슬링 헤드폰 700",
    price: 350000,
    tags: [],
    images: [
      "https://sprint-fe-project.s3.ap-northeast-2.amazonaws.com/Sprint_Mission/user/3/1721991827255/3514562.png",
    ],
    ownerId: 2,
    favoriteCount: 12,
    ownerNickname: "태연",
    isFavorite: false,
  },
  {
    id: 131,
    name: "사무용 의자",
    description: "편안한 사무용 의자",
    price: 120000,
    tags: ["가구"],
    images: [
      "https://sprint-fe-project.s3.ap-northeast-2.amazonaws.com/Sprint_Mission/user/3/1721991812368/2313561.png",
    ],
    ownerId: 3,
    favoriteCount: 4,
    ownerNickname: "유아인",
    isFavorite: false,
  },
  {
    id: 130,
    name: "스니커즈",
    description: "편안한 스니커즈",
    price: 100000,
    tags: [],
    images: [
      "https://sprint-fe-project.s3.ap-northeast-2.amazonaws.com/Sprint_Mission/user/3/1721991853452/5389615.png",
    ],
    ownerId: 4,
    favoriteCount: 10,
    ownerNickname: "이서진",
    isFavorite: false,
  },
  {
    id: 129,
    name: "레노버 노트북",
    description: "레노버 아이디어패드 5",
    price: 800000,
    tags: [],
    images: [
      "https://sprint-fe-project.s3.ap-northeast-2.amazonaws.com/Sprint_Mission/user/3/1721991798558/321351.png",
    ],
    ownerId: 5,
    favoriteCount: 4,
    ownerNickname: "박보검",
    isFavorite: false,
  },
  {
    id: 128,
    name: "갤럭시 S21",
    description: "삼성 갤럭시 S21",
    price: 600000,
    tags: [],
    images: [
      "https://sprint-fe-project.s3.ap-northeast-2.amazonaws.com/Sprint_Mission/user/3/1721991786504/31563.png",
    ],
    ownerId: 6,
    favoriteCount: 8,
    ownerNickname: "아이유",
    isFavorite: false,
  },
  {
    id: 127,
    name: "아이패드",
    description: "애플 아이패드 10.2인치",
    price: 450000,
    tags: [],
    images: [
      "https://sprint-fe-project.s3.ap-northeast-2.amazonaws.com/Sprint_Mission/user/3/1721991756711/21353.png",
    ],
    ownerId: 7,
    favoriteCount: 15,
    ownerNickname: "송중기",
    isFavorite: false,
  },
  {
    id: 126,
    name: "퀸사이즈 침대",
    description: "퀸사이즈 침대 프레임",
    price: 500000,
    tags: ["가구"],
    images: [
      "https://sprint-fe-project.s3.ap-northeast-2.amazonaws.com/Sprint_Mission/user/3/1721991744735/2113.png",
    ],
    ownerId: 8,
    favoriteCount: 6,
    ownerNickname: "전지현",
    isFavorite: false,
  },
  {
    id: 125,
    name: "판다인형",
    description: "귀여운 판다인형입니다",
    price: 30000,
    tags: [],
    images: [
      "https://sprint-fe-project.s3.ap-northeast-2.amazonaws.com/Sprint_Mission/user/3/1721991725132/233.png",
    ],
    ownerId: 9,
    favoriteCount: 7,
    ownerNickname: "윤아",
    isFavorite: false,
  },
  {
    id: 124,
    name: "맥북 프로",
    description: "애플 맥북 프로 13인치",
    price: 1500000,
    tags: [],
    images: [
      "https://sprint-fe-project.s3.ap-northeast-2.amazonaws.com/Sprint_Mission/user/3/1721991806504/31563.png",
    ],
    ownerId: 10,
    favoriteCount: 7,
    ownerNickname: "세훈",
    isFavorite: false,
  },
];
