GET  http://localhost:3000/products

###

GET  http://localhost:3000/products?keyword=

###

GET http://localhost:3000/products/66ac9bfb1c9b66ae158b935a

###

POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "테스트",
    "description": "테스트 진행중입니다",
    "price": 500,
    "tags": "테스트"
}

###

PATCH http://localhost:3000/products/66ac9bfb1c9b66ae158b935a
Content-Type: application/json

{
    "favoriteCount": 8
}

###

DELETE http://localhost:3000/products/66ac9c4e1c9b66ae158b935e