GET  http://localhost:3000/products

###

GET  http://localhost:3000/products?keyword=

###

GET http://localhost:3000/products/66bde9944a96b1598d44afd1

###

POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "테스트",
    "description": "테스트 진행중입니다",
    "price": 500,
    "tags": "테스트"
}

###

PATCH http://localhost:3000/products/66bde7a1e2d00b84e18bcee5
Content-Type: application/json

{
    "favoriteCount": 8
}

###

DELETE http://localhost:3000/products/66bde99e4a96b1598d44afd6