###
POST http://localhost:3000/auth/sign-up
Content-Type : application/json

{
    "email" : "codeit03@codeit.com",
    "password" : "!codeit03",
    "name" : "이진우",
    "nickname" : "천마랑"
}

###
POST http://localhost:3000/auth/sign-in
Content-Type : application/json

{
    "email" : "codeit01@codeit.com",
    "password" : "!codeit01"
}

### 
POST http://localhost:3000/auth/refresh-token
Content-Type : application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRkNzAwNWJlLWU3YTctNGNkZi04NTE3LTE2YmVjMjUzOGEwMiIsImlhdCI6MTcyODI4OTE4OCwiZXhwIjoxNzI4ODkzOTg4fQ.FEFZMgPw6QM0ClNygWWxBd_ljfV28rssQoTcTobAAwI"
}

# email : "codeit02@codeit.com"
###
POST http://localhost:3000/auth/sign-up
Content-Type : application/json

{
    "email" : "codeit02@codeit.com",
    "password" : "!codeit01",
    "name" : "이진우",
    "nickname" : "설랑"
}

###
POST http://localhost:3000/auth/sign-in
Content-Type : application/json

{
    "email" : "codeit02@codeit.com",
    "password" : "!codeit01"
}

### 
POST http://localhost:3000/auth/refresh-token
Content-Type : application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlmYmEwODRjLTgzZDgtNDAwMC04ZjI5LWE1MzIyMTZkN2YyYyIsImlhdCI6MTcyODU0MzIwNSwiZXhwIjoxNzI5MTQ4MDA1fQ.4-Loi9CwMO6Su245b-iILazxgBzymaqNLXXXH56xT-U"
}