###
POST http://localhost:3000/product/ef18bb26-0ea2-4e25-bb63-615ec48d9341/comment
Content-Type : application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlmYmEwODRjLTgzZDgtNDAwMC04ZjI5LWE1MzIyMTZkN2YyYyIsImlhdCI6MTcyODU0MzIwNSwiZXhwIjoxNzI4ODAyNDA1fQ.HJaPsEZMBiNGr1tPQV0HpHZOcpX-NXVm1fMJeA4IEAA

{
    "content" : "댓글 추가2"
}

###
GET http://localhost:3000/product/ef18bb26-0ea2-4e25-bb63-615ec48d9341/comment
Content-Type : application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlmYmEwODRjLTgzZDgtNDAwMC04ZjI5LWE1MzIyMTZkN2YyYyIsImlhdCI6MTcyODU0MzIwNSwiZXhwIjoxNzI4ODAyNDA1fQ.HJaPsEZMBiNGr1tPQV0HpHZOcpX-NXVm1fMJeA4IEAA

###
GET http://localhost:3000/product/comment/9590c57e-1e3f-4eb4-965f-ba43bd3b85d9
Content-Type : application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlmYmEwODRjLTgzZDgtNDAwMC04ZjI5LWE1MzIyMTZkN2YyYyIsImlhdCI6MTcyODU0MzIwNSwiZXhwIjoxNzI4ODAyNDA1fQ.HJaPsEZMBiNGr1tPQV0HpHZOcpX-NXVm1fMJeA4IEAA

###
PATCH http://localhost:3000/product/comment/9590c57e-1e3f-4eb4-965f-ba43bd3b85d9
Content-Type : application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlmYmEwODRjLTgzZDgtNDAwMC04ZjI5LWE1MzIyMTZkN2YyYyIsImlhdCI6MTcyODU0MzIwNSwiZXhwIjoxNzI4ODAyNDA1fQ.HJaPsEZMBiNGr1tPQV0HpHZOcpX-NXVm1fMJeA4IEAA

{
    "content" : "댓글2 수정"
}

###
DELETE http://localhost:3000/product/comment/4ef3cb91-2f61-4627-80f8-037e8757ef30
Content-Type : application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlmYmEwODRjLTgzZDgtNDAwMC04ZjI5LWE1MzIyMTZkN2YyYyIsImlhdCI6MTcyODU0MzIwNSwiZXhwIjoxNzI4ODAyNDA1fQ.HJaPsEZMBiNGr1tPQV0HpHZOcpX-NXVm1fMJeA4IEAA
