###
POST http://localhost:3000/products
Content-Type : application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRkNzAwNWJlLWU3YTctNGNkZi04NTE3LTE2YmVjMjUzOGEwMiIsImlhdCI6MTcyODUyNzAxNSwiZXhwIjoxNzI4Nzg2MjE1fQ.NirtWHfa1lfusE2rX1OYsVFcnmClXcXmKKDnLvpEBB4

{
    "name" : "테스트 상품 등록3",
    "description" : "상품 설명3",
    "price" : 666666,
    "images" : ["https://ifh.cc/g/GvzJSH.png", "https://ifh.cc/g/Jv7bzz.png"],
    "tags" : ["태그1", "태그2", "12345678901234567890123456789012345678901234567890"] 
}

###
GET http://localhost:3000/products
Content-Type : application/json

###
GET http://localhost:3000/products
Content-Type : application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRkNzAwNWJlLWU3YTctNGNkZi04NTE3LTE2YmVjMjUzOGEwMiIsImlhdCI6MTcyODUyNzAxNSwiZXhwIjoxNzI4Nzg2MjE1fQ.NirtWHfa1lfusE2rX1OYsVFcnmClXcXmKKDnLvpEBB4


###
GET http://localhost:3000/products/ef18bb26-0ea2-4e25-bb63-615ec48d9341
Content-Type : application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRkNzAwNWJlLWU3YTctNGNkZi04NTE3LTE2YmVjMjUzOGEwMiIsImlhdCI6MTcyODUyNzAxNSwiZXhwIjoxNzI4Nzg2MjE1fQ.NirtWHfa1lfusE2rX1OYsVFcnmClXcXmKKDnLvpEBB4

###
PATCH http://localhost:3000/products/ef18bb26-0ea2-4e25-bb63-615ec48d9341
Content-Type : application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRkNzAwNWJlLWU3YTctNGNkZi04NTE3LTE2YmVjMjUzOGEwMiIsImlhdCI6MTcyODUyNzAxNSwiZXhwIjoxNzI4Nzg2MjE1fQ.NirtWHfa1lfusE2rX1OYsVFcnmClXcXmKKDnLvpEBB4

{
    "name" : "테스트 상품 등록3 수정",
    "description" : "상품 설명3 수정",
    "price" : 999999,
    "images" : ["https://ifh.cc/g/GvzJSH.png", "https://ifh.cc/g/Jv7bzz.png", "https://ifh.cc/g/Jv7bzz2.png"],
    "tags" : ["태그1", "태그2"] 
}

###
DELETE http://localhost:3000/products/4f0b65ab-28fb-449c-bd94-1088eb665122
Content-Type : application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRkNzAwNWJlLWU3YTctNGNkZi04NTE3LTE2YmVjMjUzOGEwMiIsImlhdCI6MTcyODUyNzAxNSwiZXhwIjoxNzI4Nzg2MjE1fQ.NirtWHfa1lfusE2rX1OYsVFcnmClXcXmKKDnLvpEBB4




# email : "codeit02@codeit.com"

###
GET http://localhost:3000/products
Content-Type : application/json

###
GET http://localhost:3000/products
Content-Type : application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlmYmEwODRjLTgzZDgtNDAwMC04ZjI5LWE1MzIyMTZkN2YyYyIsImlhdCI6MTcyODU0MzIwNSwiZXhwIjoxNzI4ODAyNDA1fQ.HJaPsEZMBiNGr1tPQV0HpHZOcpX-NXVm1fMJeA4IEAA

###
POST http://localhost:3000/products/ef18bb26-0ea2-4e25-bb63-615ec48d9341/favorite
Content-Type : application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlmYmEwODRjLTgzZDgtNDAwMC04ZjI5LWE1MzIyMTZkN2YyYyIsImlhdCI6MTcyODU0MzIwNSwiZXhwIjoxNzI4ODAyNDA1fQ.HJaPsEZMBiNGr1tPQV0HpHZOcpX-NXVm1fMJeA4IEAA

###
DELETE http://localhost:3000/products/ef18bb26-0ea2-4e25-bb63-615ec48d9341/favorite
Content-Type : application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlmYmEwODRjLTgzZDgtNDAwMC04ZjI5LWE1MzIyMTZkN2YyYyIsImlhdCI6MTcyODU0MzIwNSwiZXhwIjoxNzI4ODAyNDA1fQ.HJaPsEZMBiNGr1tPQV0HpHZOcpX-NXVm1fMJeA4IEAA