###
GET http://localhost:3000/users/me
Content-Type : application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5YTllNzFjLWM1ODYtNGEwYS1hNTgzLTBiMTIxOGM0YzQwNiIsImlhdCI6MTcyODI3OTEyMSwiZXhwIjoxNzI4NTM4MzIxfQ.E72W4Ih413PEUChspfUHcugMfh3L7K79oqi7iec7FPM

### 
PATCH http://localhost:3000/users/me
Content-Type : application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5YTllNzFjLWM1ODYtNGEwYS1hNTgzLTBiMTIxOGM0YzQwNiIsImlhdCI6MTcyODI3OTEyMSwiZXhwIjoxNzI4NTM4MzIxfQ.E72W4Ih413PEUChspfUHcugMfh3L7K79oqi7iec7FPM

{
    "nickname" : "설랑"
}

### 
PATCH http://localhost:3000/users/password
Content-Type : application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5YTllNzFjLWM1ODYtNGEwYS1hNTgzLTBiMTIxOGM0YzQwNiIsImlhdCI6MTcyODI3OTEyMSwiZXhwIjoxNzI4NTM4MzIxfQ.E72W4Ih413PEUChspfUHcugMfh3L7K79oqi7iec7FPM

{
    "password" : "!codeit01",
    "currentPassword" : "codeit01!"
}