GET  http://localhost:3001/article
###

GET  http://localhost:3001/article?keyWord=post&page=&pageSize=

###

GET http://localhost:3001/article/d99d5b4a-b957-4211-a01e-e1a5a8fe1d58
###

POST http://localhost:3001/article
Content-Type: application/json

{
    "title": "테스트 post1",
    "content": "테스트 post1"
}


###

PATCH http://localhost:3001/article/d99d5b4a-b957-4211-a01e-e1a5a8fe1d58
Content-Type: application/json

{
    "title": "게시물 수정 테스트"
}


###

DELETE http://localhost:3001/article/329c83eb-ff90-4cc4-b2b0-0b1528864d2d