GET  http://localhost:3001/article
###

GET  http://localhost:3001/article?keyWord=post&page=&pageSize=

###

GET http://localhost:3001/article/d99d5b4a-b957-4211-a01e-e1a5a8fe1d58
###

POST http://localhost:3001/article
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YmU2Nzk0Ni03ZGMwLTQ4YjEtOTM2OC0xNWFjNzc2M2RhMTAiLCJpYXQiOjE3Mjg1MjgyMDEsImV4cCI6MTcyODUzMTgwMX0.Xh75f0_Eh888t4TTW5MOwAYTDT12eKPkAoIaABuL4Qw
Content-Type: application/json

{
    "title": "테스트",
    "content": "xotmxm 3"
}


###

PATCH http://localhost:3001/article/1792c900-891b-47b8-aaae-9f184d904841
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YmU2Nzk0Ni03ZGMwLTQ4YjEtOTM2OC0xNWFjNzc2M2RhMTAiLCJpYXQiOjE3MjgyODk0OTksImV4cCI6MTcyODI5MzA5OX0.OHeymlkZUYKNVTEUITb0xv24sqZ011ewjXzox2gpfx4
Content-Type: application/json

{
    "title": "게시물 수정 테스트"
}


###

DELETE http://localhost:3001/article/1792c900-891b-47b8-aaae-9f184d904841
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjM4MmU0ZC0wNDRkLTRmMzAtYmJiYy0xODk2NDg2ZjFlYjYiLCJpYXQiOjE3MjgyODY5ODksImV4cCI6MTcyODI5MDU4OX0.OxNxs4OBYzu37P7gpi0DCNokRDVzSC44M68MgGTlurM
