GET  http://localhost:3001/article/6e8d93de-f480-488a-9215-8a623631ab35/comment

###

GET  http://localhost:3001/article/d99d5b4a-b957-4211-a01e-e1a5a8fe1d58/comment?cursor=b3d9248e-3f97-467a-ab9d-607dec041cf0

###

POST http://localhost:3001/article/6e8d93de-f480-488a-9215-8a623631ab35/comment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjM4MmU0ZC0wNDRkLTRmMzAtYmJiYy0xODk2NDg2ZjFlYjYiLCJpYXQiOjE3MjgyODY5ODksImV4cCI6MTcyODI5MDU4OX0.OxNxs4OBYzu37P7gpi0DCNokRDVzSC44M68MgGTlurM
Content-Type: application/json

{
    "content": "123"
}

###
GET  http://localhost:3001/product/192fce08-09c2-4065-981b-0285f0e452b8/comment

###

GET  http://localhost:3001/product/46704eb4-515d-4374-95f1-85de39463121/comment?pageSize=4&cursor=50aff497-0bea-4f37-a5e3-dadda6af3552
###

POST http://localhost:3001/product/5b951caa-a747-4ab2-a274-f077708118b5/comment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YmU2Nzk0Ni03ZGMwLTQ4YjEtOTM2OC0xNWFjNzc2M2RhMTAiLCJpYXQiOjE3Mjg1NDQyNzgsImV4cCI6MTcyODU0Nzg3OH0.x0YwlMA5SnWCnDmeasr457rhvMJggZd2wyiz3P_cDjI
Content-Type: application/json

{
    "content": "안녕?"
}

###
PATCH http://localhost:3001/comment/48651b38-2a67-4926-bb01-ce7859843da7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjM4MmU0ZC0wNDRkLTRmMzAtYmJiYy0xODk2NDg2ZjFlYjYiLCJpYXQiOjE3MjgyODY5ODksImV4cCI6MTcyODI5MDU4OX0.OxNxs4OBYzu37P7gpi0DCNokRDVzSC44M68MgGTlurM
Content-Type: application/json

{
    "content": "댓글 수정 테스트"
}

###
DELETE http://localhost:3001/comment/48651b38-2a67-4926-bb01-ce7859843da7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjM4MmU0ZC0wNDRkLTRmMzAtYmJiYy0xODk2NDg2ZjFlYjYiLCJpYXQiOjE3MjgyODY5ODksImV4cCI6MTcyODI5MDU4OX0.OxNxs4OBYzu37P7gpi0DCNokRDVzSC44M68MgGTlurM