GET  http://localhost:3000/freeCommends

###

GET  http://localhost:3000/freeCommends/?cursor=136bb431-ac7b-42d5-8b9d-f1cd3ce88d89

###

GET http://localhost:3000/freeCommends/22938169-e14e-4eb4-b2e0-0249d0c874da

###

POST http://localhost:3000/freeCommends
Content-Type: application/json

{
    "content": "fdg",
    "userId": "412aab2b-26fe-4d60-9006-8459c869580f",
    "noticeBoardId": "0c5d059b-ee21-4126-87a4-582c6cd39677"
}

###

PATCH http://localhost:3000/freeCommends/ce07a21b-63ea-4e66-97d8-8537813c5d0b
Content-Type: application/json

{
    "content": "fds"
}

###

DELETE http://localhost:3000/freeCommends/ce07a21b-63ea-4e66-97d8-8537813c5d0b