GET  http://localhost:3001/noticeBoards/5fa13fdb-caf1-46b5-bedb-108c66c3adfe/freeCommends

###

GET  http://localhost:3000/freeCommends/?cursor=136bb431-ac7b-42d5-8b9d-f1cd3ce88d89

###

GET http://localhost:3000/freeCommends/22938169-e14e-4eb4-b2e0-0249d0c874da

###

POST http://localhost:3001/freeCommends
Content-Type: application/json

{
    "content": "fdgs",
    "noticeBoardId": "5fa13fdb-caf1-46b5-bedb-108c66c3adfe"
}

###

PATCH http://localhost:3000/freeCommends/ce07a21b-63ea-4e66-97d8-8537813c5d0b
Content-Type: application/json

{
    "content": "fds"
}

###

DELETE http://localhost:3001/freeCommends/a9767bcc-e79e-499f-893f-ad84c3646716