POST http://localhost:3001/article/934ceb0e-ac96-45df-806f-73f4572f6fc4/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YmU2Nzk0Ni03ZGMwLTQ4YjEtOTM2OC0xNWFjNzc2M2RhMTAiLCJpYXQiOjE3Mjg1MjM0NDksImV4cCI6MTcyODUyNzA0OX0.st41MtkbZNWXAcCP6VCTYQwmrAybVPmON5TW6VSDLeg
Content-Type: application/json