POST http://localhost:3001/article/d2bee68d-2ff9-4b36-8b87-476bfacefa79/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YmU2Nzk0Ni03ZGMwLTQ4YjEtOTM2OC0xNWFjNzc2M2RhMTAiLCJpYXQiOjE3Mjg1MjgyMDEsImV4cCI6MTcyODUzMTgwMX0.Xh75f0_Eh888t4TTW5MOwAYTDT12eKPkAoIaABuL4Qw
Content-Type: application/json