POST http://localhost:3001/product
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyZjJkNDBhZC0yZGNjLTRhMjctOTgxZi00Nzk1OWRiNzA3NDMiLCJpYXQiOjE3MjgyODIwMjksImV4cCI6MTcyODI4NTYyOX0.7eDHRNvo2pw7gDM8gBpv3XFGtoQil5h7oWrzt6ljooc
Content-Type: application/json

{
    "name": "테스트 3",
    "description": "테스트",
    "price": 0,
    "tags": []
}