GET  http://localhost:3000/usedCommends

###

GET  http://localhost:3000/usedCommends?cursor=5f04ea72-41d8-4824-92ca-437bffbd4beb

###

GET http://localhost:3000/usedCommends/5f04ea72-41d8-4824-92ca-437bffbd4beb

###

POST http://localhost:3000/usedCommends
Content-Type: application/json

{
    "content": "fg",
    "userId": "412aab2b-26fe-4d60-9006-8459c869580f",
    "usedMarketId": "c8ce69c0-2bc4-44dd-9f90-82df2047919d"
}


###

PATCH http://localhost:3000/usedCommends/c0f7d2fe-bee4-4bbb-9618-70bcc4a820e0
Content-Type: application/json

{
    "content": "456"
}


###

DELETE http://localhost:3000/usedCommends/c0f7d2fe-bee4-4bbb-9618-70bcc4a820e0