GET  http://localhost:3000/users

###

GET  http://localhost:3000/users

###

GET http://localhost:3000/users/22938169-e14e-4eb4-b2e0-0249d0c874da

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "테스트"
}

###

PATCH http://localhost:3000/users/49e3d6f5-36dd-481d-8db3-abe73aea8ced
Content-Type: application/json

{
    "name": "keyBoardWarrior"
}

###

DELETE http://localhost:3000/users/66ac9c4e1c9b66ae158b935e