### 회원가입
POST http://localhost:3000/auth/signUp
Content-Type: application/json

{
  "email": "testuser@example.com",
  "nickname": "테스트",
  "password": "testpassword",
  "passwordConfirmation": "testpassword"
}


### 로그인
POST http://localhost:3000/auth/signIn
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "testpassword"
}
