### 회원가입
POST https://one-sprint-mission-be-fv23.onrender.com/auth/signUp
Content-Type: application/json

{
  "email": "aibao0005@naver.com",
  "nickname": "테스트",
  "password": "wns0423^^",
  "passwordConfirmation": "wns0423^^"
}


### 로그인
POST http://one-sprint-mission-be-fv23.onrender.com/auth/signIn
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "testpassword"
}
