POST http://localhost:3000/products/182/comments
Content-Type: application/json

{
  "content": "중고마켓 댓글 테스트 삽입"
}

###

POST http://localhost:3000/articles/7/comments
Content-Type: application/json

{
  "content": "자유게시판 댓글 테스트 삽입"
}

###

GET http://localhost:3000/products/182/comments

###

GET http://localhost:3000/articles/2/comments

###

PATCH  http://localhost:3000/comments/2
Content-Type: application/json

{
  "content": "자유게시판 댓글 수정 테스트"
}

###

DELETE http://localhost:3000/comments/2