### GET /products
GET http://localhost:3000/api/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ODdmMGJlZS1mMWE3LTRlMmMtODlhOS0yMWNmNzg1NWUxM2UiLCJpYXQiOjE3MjgzMTM4ODQsImV4cCI6MTcyODMxNzQ4NH0.RsWgJtFS4-GxndU9jGiIjUhXVA7MunwW_59_WEWng6o

### POST /products
POST http://localhost:3000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ODdmMGJlZS1mMWE3LTRlMmMtODlhOS0yMWNmNzg1NWUxM2UiLCJpYXQiOjE3MjgzMTM4ODQsImV4cCI6MTcyODMxNzQ4NH0.RsWgJtFS4-GxndU9jGiIjUhXVA7MunwW_59_WEWng6o

{
      "name": "새로운 상품 이름입니다.",
      "description": "새로운 상품 내용입니다.",
      "price": 1234,
      "tags":["상품", "태그"]
} 



### GET /products/{productId}
GET http://localhost:3000/api/products/241cc1e3-df67-4530-85ac-7e2277f61fa8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ODdmMGJlZS1mMWE3LTRlMmMtODlhOS0yMWNmNzg1NWUxM2UiLCJpYXQiOjE3MjgzMTM4ODQsImV4cCI6MTcyODMxNzQ4NH0.RsWgJtFS4-GxndU9jGiIjUhXVA7MunwW_59_WEWng6o


### PATCH /products/{productId}
PATCH http://localhost:3000/api/products/241cc1e3-df67-4530-85ac-7e2277f61fa8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ODdmMGJlZS1mMWE3LTRlMmMtODlhOS0yMWNmNzg1NWUxM2UiLCJpYXQiOjE3MjgzMTM4ODQsImV4cCI6MTcyODMxNzQ4NH0.RsWgJtFS4-GxndU9jGiIjUhXVA7MunwW_59_WEWng6o


{
      "name": "수정된 상품 이름입니다.",
      "description": "수정된 상품 내용입니다.",
      "price": 10000,
      "tags":["수정", "했다"]
} 


### DELETE /products/{productId}
DELETE http://localhost:3000/api/products/241cc1e3-df67-4530-85ac-7e2277f61fa8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ODdmMGJlZS1mMWE3LTRlMmMtODlhOS0yMWNmNzg1NWUxM2UiLCJpYXQiOjE3MjgzMTM4ODQsImV4cCI6MTcyODMxNzQ4NH0.RsWgJtFS4-GxndU9jGiIjUhXVA7MunwW_59_WEWng6o

### POST /products/{productId}/favorite
POST http://localhost:3000/api/products/13e88c48-b497-44ed-802e-41c02b4cffd1/favorite
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ODdmMGJlZS1mMWE3LTRlMmMtODlhOS0yMWNmNzg1NWUxM2UiLCJpYXQiOjE3MjgzMTM4ODQsImV4cCI6MTcyODMxNzQ4NH0.RsWgJtFS4-GxndU9jGiIjUhXVA7MunwW_59_WEWng6o

### DELETE /products/{productId}/favorite
DELETE http://localhost:3000/api/products/13e88c48-b497-44ed-802e-41c02b4cffd1/favorite
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ODdmMGJlZS1mMWE3LTRlMmMtODlhOS0yMWNmNzg1NWUxM2UiLCJpYXQiOjE3MjgzMTM4ODQsImV4cCI6MTcyODMxNzQ4NH0.RsWgJtFS4-GxndU9jGiIjUhXVA7MunwW_59_WEWng6o
